.Dockerignore, Dockerfile
Dev 서버용 Dockerfile 및 .dockerignore 파일을 추가하였습니다.
이 PR은 개발 환경에서 컨테이너 실행을 위한 초기 설정을 포함합니다.
- Resolves #[이슈 번호]
1.  Dockerfile 추가
- Dev 서버용 Dockerfile 설정
- 컨테이너 실행을 위한 기본 환경 구성
2. .dockerignore 추가
- 불필요한 파일을 Docker 빌드에서 제외하여 빌드 최적화
1. Dockerfile을 사용하여 로컬 개발 환경에서 컨테이너 빌드 및 실행 테스트
2. .dockerignore가 정상적으로 적용되는지 확인
이후 Dev 서버용 설정이 추가되면 Dockerfile 업데이트가 필요할 수 있음.
=> ✨ Feature - Dev 서버용 Dockerfile 및 .dockerignore 추가

.github/workflows/cicd.yml, Dockerfile, vite.config.ts
Vite 프리뷰 서버 설정을 추가하고, Dockerfile에서 환경 변수를 적용하였습니다.  
또한, CI/CD 파이프라인을 설정하여 ECR에 이미지를 빌드 및 푸시하고, EC2에서 자동 배포하도록 구성하였습니다.
- Resolves #[이슈 번호]
1. Vite preview 서버 설정 추가 (`vite.config.ts`)
2. Dockerfile에서 `VITE_HOST` 환경 변수 적용 및 `CMD` 실행 명령어 수정
3. GitHub Actions 기반 CI/CD 파이프라인 추가
- ECR 로그인 및 Docker 이미지 빌드/푸시
- EC2에서 최신 버전 자동 배포 (블루-그린 방식)
- Nginx 설정 변경 및 자동 롤백 기능 추가
1. 로컬에서 Vite 프리뷰 서버 실행 (`yarn preview`)
2. Docker 컨테이너에서 Vite 서버 정상 작동 확인 (`docker run`)
배포 테스트 과정 중 cicd.yml 파일이 변경 될 수 있습니다.
추가적인 리뷰가 필요한 부분이 있다면 코멘트 부탁드립니다. 🚀
=> ✨ Feature - CI/CD pipeline and Vite preview server configuration

.github/workflows/cicd.yml
CI/CD 파이프라인을 개선하여 Amazon ECR 이미지 태깅 방식 및 EC2 배포 로직을 수정하였습니다.  
기존 방식에서 최신 태그를 가져오는 로직을 수정하고, Nginx 및 포트 설정을 최적화했습니다.
- Resolves #[이슈 번호]
1. Docker 이미지 태깅 시 `latest` 태그 추가 및 최신 태그 가져오는 방식 변경
2. EC2 배포 스크립트 개선:
- AWS ECR 로그인 방식 수정 (`$AWS_REGION` 변수 활용)
- EC2에서 최신 이미지 태그를 조회하여 사용하도록 변경
- 기존 컨테이너 포트 확인 후 블루-그린 방식 적용 (`4173` ↔ `4174`)
- Nginx 설정 변경 시 자동 테스트 및 적용 (`nginx -t && systemctl reload nginx`)
1. GitHub Actions를 이용한 `dev` 브랜치에서 CI/CD 실행 확인
2. Amazon ECR에서 최신 이미지 태그 조회 테스트 (`aws ecr describe-images`)
3. EC2에서 배포 스크립트 실행 및 Nginx 적용 테스트
EC2 배포 시 문제가 발생할 경우, Nginx 설정을 수동으로 확인해주세요.  
추가적인 리뷰가 필요한 부분이 있다면 코멘트 부탁드립니다. 🚀
=> ✨ Feature - Update CI/CD pipeline for improved ECR and EC2 deployment

dev-dist/sw.js, src/meetDone/page/MeetDone.tsx, src/router.tsx
모임 종료 화면 UI 구현, API 연결 및 페이지간 라우팅 구현 전
- Resolves #14 
1. MeetDone.tsx
=> ✨ Feature - 모임 종료 화면 UI 구현

dev-dist/sw.js, src/main/hooks/useMeetData.tsx, src/main/services/fetchUser.ts, src/main/services/getMeetsService.ts
=> ✨ Feature - 메인 페이지의 모임 목록 조회 api 연동

.github/workflows/cicd.yml
Vite 프로젝트 배포를 위한 GitHub Actions 워크플로우에서 CloudFront 캐시 무효화 및 빌드 환경 변수 주입 기능을 추가했습니다.
이를 통해 배포 후 캐시 반영이 바로 이루어지며, 빌드 시점에 필요한 민감 정보들을 안전하게 주입할 수 있습니다.
- Resolves #[이슈 번호]
3. Vite 빌드 환경에 VITE_ 접두어가 붙은 환경변수들을 주입하도록 워크플로우 수정
4. 민감한 API 키 값은 GitHub Secrets로 관리
=> feat: 환경변수 추가

.github/workflows/cicd-prod.yml
Prod CICD yml 파일에 빌드시 들어가는 환경변수 값 추가
=> ✨ Feature - 환경변수 추가 (Prod)

package.json, src/common/page/Splash.tsx, src/login/page/LoginRedirect.tsx, src/router.tsx, yarn.lock
- 스플래시 화면을 구현합니다.
- Resolves #37 
1. 기존의 정적인 스플래시 화면에 애니메이션 기능을 추가했습니다.
https://github.com/user-attachments/assets/cd1f8ec8-ecf6-44b7-a3e7-ade19368f89e
=> ✨ Feature - 스플래시 페이지 구현

dev-dist/sw.js, src/meetChat/components/chatInput.tsx, src/meetChat/hooks/useChatSocket.tsx, src/utils/formatChatDate.ts
=> ✨ Feature - 채팅 엔터키 구현 및 채팅 시간 오류 수정

dev-dist/sw.js, src/common/components/Header.tsx, src/common/components/ProtectedRoute.tsx, src/common/components/RedirectIfAuthenticated.tsx, src/common/page/Splash.tsx, src/global.css, src/login/page/Login.tsx, src/main/hooks/useMeetData.tsx, src/main/page/Main.tsx, src/main/services/getMeetsService.ts, src/meetCreate(update)/hooks/useCreateMeetOther.tsx, src/meetCreate(update)/hooks/useCreateMeetSubmit.ts, src/meetCreate(update)/hooks/useCreateMeetType.tsx, src/meetCreate(update)/page/CreateMeetOther.tsx, src/meetCreate(update)/page/CreateMeetPlace.tsx, src/meetCreate(update)/types/createMeetResponse.ts, src/meetDetail/components/HeaderDropbox.tsx, src/meetDetail/page/MeetDetail.tsx, src/my/components/MySekeleton.tsx, src/my/components/UserInfoSkeleton.tsx, src/my/hooks/useMyPage.tsx, src/my/page/My.tsx, src/router.tsx
- 스플래시 화면 적용
- 페이지 접근 제한
- 전체적인 에러 픽스
=> 🐛 Fix - 스플래시 화면 적용 및 전체적인 에러 픽스

dev-dist/sw.js, package.json, src/main.tsx, src/meetDetail/page/MeetDetail.tsx, yarn.lock
- 모인 링크 공유시 모임 미리보기 기능 구현
- strict mode 제거
=> ✨ Feature - 링크 공유시 모임 미리보기 기능 구현

src/meetCreate(update)/hooks/useCreateMeetOther.tsx
- 모임 생성 및 수정 페이지 마지막 단계의 버튼 활성, 비활성 로직 강화
=> 🐛 Fix - 모임 생성 마지막 단계 버튼 상태 관리

dev-dist/sw.js, src/main/hooks/useMeetData.tsx, src/main/page/Main.tsx
- 메인 페이지에 무한 스크롤을 구현하였습니다.
- Resolves #47
=> ✨ Feature - 메인 페이지 무한 스크롤 구현

dev-dist/sw.js, src/common/types/meetType.ts, src/meetDetail/components/Toggle.tsx, src/meetDetail/hooks/useDebouncedToggle.tsx, src/meetDetail/page/MeetDetail.tsx
- 모임 상세 페이지에서 멤버의 정산 여부 업데이트가 정상적으로 반영되도록 수정하였습니다.
- 토글 반영이 늦어 불편하다는 팀원의 의견을 반영하여 기존의 delay 시간 700을 300으로 수정하였습니다.
=> 🐛 Fix - 멤버의 정산 내역 업데이트 토글 관련 에러 픽스

src/meetCreate(update)/hooks/useCreateMeetSubmit.ts, src/meetCreate(update)/page/CreateMeetPlace.tsx, src/meetDetail/components/KakaoMap.tsx, src/meetDetail/page/MeetDetail.tsx
- 모임 생성 후 모임 생성에 사용된 데이터 초기화 처리
- 모임 생성 후 중복 토스트 메세지가 보이는 에러 픽스
- 모임 생성시 지도의 최대 줌아웃 설정
- 비용이 발생하지 않는 모임의 경우, 비용 섹션을 숨김 처리
=> 🐛 Fix - 모임 생성 후 모임 생성에 사용된 데이터 초기화 처리, 모임 생성 후 중복 토스트 메세지가 보이는 에러 픽스, 모임 생성시 지도 최대 줌아웃 설정, 비용이 발생하지 않는 모임의 비용 섹션 숨김 처리

dev-dist/sw.js, firebase.ts, package.json, public/firebase-messaging-sw.js, src/login/page/LoginRedirect.tsx, src/main.tsx, src/utils/fcm.ts, yarn.lock
- FCM 알림 테스트용 코드 작성
- 브라우저의 FCM 토큰 발급까지 완료
- Resolves #62 
- `firebase` 의존성이 추가되었습니다.
=> ✨ Feature - 로그인시 FCM 토큰 발급

dev-dist/sw.js, src/main/page/Main.tsx, src/meetCreate(update)/hooks/useCreateMeetOther.tsx, src/meetCreate(update)/hooks/useCreateMeetPlace.tsx, src/meetCreate(update)/page/CreateMeetOther.tsx, src/meetCreate(update)/page/CreateMeetPlace.tsx, src/meetCreate(update)/store/useCreateMeetStore.ts
새로고침, 이전페이지 이동에서도 모임 생성 데이터 유지
=> ✨ Fix - 새로고침, 이전페이지 이동에서도 모임 생성 데이터 유지

dev-dist/sw.js, src/main/hooks/useMeetData.tsx, src/main/page/Main.tsx
처음 페이지 접근 시 스플래쉬 화면이 조금 늦게 로딩되는 문제 해결
=> ✨ Fix - 처음 페이지 접근 시 스플래쉬 화면이 조금 늦게 로딩됨

src/common/components/Header.tsx
=> ✨ Feature-  로그인 하지 않은 경우, 로그인 버튼 보이기

src/main/page/Main.tsx
- 미로그인시 로그인 페이지로 리다이렉트 되기 전 메인 페이지가 보이는 오류 픽스
- Resolves #70 
https://github.com/user-attachments/assets/0a416d19-1b53-41cc-a76c-de4c9b85224f
=> 🐛 FIX - 미로그인시 로그인 페이지로 리다이렉트 되기 전 메인 페이지가 보이는 오류 픽스

src/meetDetail/page/MeetDetail.tsx
- 종료된 모임의 경우에도 모임 멤버의 결제 업데이트 토글을 수정할 수 있는 에러 픽스
=> 🐛 FIX - 종료된 모임의 경우에도 모임 멤버의 결제 업데이트 토글을 수정할 수 있는 에러 픽스

src/main/page/Main.tsx
- 유저가 참여한 모임이 없는 경우, 관련 텍스트를 출력합니다.
=> 🐛 FIX - 모임이 없는 경우에 메인 페이지에 텍스트 출력

src/meetChat/hooks/useChatSocket.tsx, src/utils/formatChatDate.ts
=> 🐛 Fix - 채팅 시간 조정 삭제

src/main/page/Main.tsx
- 메인 페이지에 모임이 없는 경우의 텍스트가 잠깐 보였다가 사라지는 오류 픽스
- Resolves #79 
https://github.com/user-attachments/assets/b5f26f32-6a6f-481f-96d1-85414ed163f0
=> 🐛 Fix - 메인 페이지에 모임이 없는 경우의 텍스트가 잠깐 보였다가 사라지는 오류 픽스

package.json, src/meetCreate(update)/hooks/useCreateMeetOther.tsx, src/meetCreate(update)/store/useCreateMeetStore.ts, src/utils/convertMeetTypeToMeetInfo.ts, yarn.lock
- 현재 모인 인원보다 적은 인원으로 모임 인원 수정이 가능한 오류 픽스
- Resolves #81
=> 🐛 Fix -  현재 모인 인원보다 적은 인원으로 모임 인원 수정이 가능한 오류 픽스

src/my/hooks/useMyPage.tsx
- 로그아웃시 FCM 토큰 비동기 삭제 처리
- 
- Resolves #85
=> 🐛 Fix - 로그아웃시 FCM 토큰 비동기 삭제 처리

dev-dist/sw.js, src/common/components/Header.tsx, src/global.css, src/main/components/CreateButton.tsx
- 화면의 max width 설정
- Resolves #84
=> 💄 Design - 화면의 max width 설정

public/firebase-messaging-sw.js, src/__fcm__/fcm.ts, src/common/components/Header.tsx, src/common/hooks/useHeaderContirmModal.tsx, src/common/page/Splash.tsx, src/common/types/headerType.ts, src/main/components/CreateButton.tsx, src/main/components/MeetChip.tsx, src/main/components/MeetTab.tsx, src/meetChat/components/chatInput.tsx, src/meetChat/page/MeetChat.tsx, src/meetCreate(update)/components/CategoryBox.tsx, src/meetCreate(update)/components/CostToggle.tsx, src/meetCreate(update)/components/MeetInputField.tsx, src/meetCreate(update)/components/TimePicker.tsx, src/meetCreate(update)/hooks/useCreateMeetOther.tsx, src/meetCreate(update)/page/CreateMeetLast.tsx, src/meetCreate(update)/page/CreateMeetOther.tsx, src/meetCreate(update)/page/CreateMeetPlace.tsx, src/meetCreate(update)/page/CreateMeetType.tsx, src/meetCreate(update)/styles/timepicker.css, src/meetDetail/components/HeaderDropbox.tsx, src/meetDetail/hooks/useMeetStore.tsx, src/meetDetail/page/MeetDetail.tsx, src/meetDone/page/MeetDone.tsx, src/meetPaying/hooks/useMeetPaying.tsx, src/meetPaying/page/MeetPaying.tsx, sw.js
- 화면 max-width 수정으로 인한 전반적인 CSS 수정 및 보완
- 모임 상세 > 햄버거 버튼의 "정산하기" 버튼 클릭 > 정산하기 페이지 진입시, 모임 비용 범위에 대한 유효성 검사 로직 추가 (1,000원 이상 10,000,000원 이하)
- Resolves #89
=> 🐛 Fix - 화면 max-width 수정으로 인한 전반적인 CSS 수정 및 보완

src/main/components/CreateButton.tsx
=> fix: 모임 생성 버튼이 안 보이는 문제 해결 (긴급!)

src/common/components/Header.tsx, src/common/hooks/useHeaderContirmModal.tsx, src/meetCreate(update)/components/LoadingMap.tsx, src/meetCreate(update)/components/MarkerInfoWindow.tsx, src/meetCreate(update)/hooks/useCreateMeetPlace.tsx, src/meetCreate(update)/page/CreateMeetPlace.tsx, src/meetDetail/services/completeMeetService.tsx, src/router.tsx
- 모임 삭제/종료/나가기 동작시 노출되던 alert를 제거하였습니다.
- 모임 생성 단계에서 좌표의 주소가 즉각적으로 업데이트 되지 않던 오류를 픽스하였습니다.
- 위치 권한 비허용시, 모임 생성 단계 중 2번째 단계인 장소 설정 페이지에서 토스트 메세지와 텍스트를 통해 유저에게 위치 권한 요청을 명시적으로 요청합니다.
- 존재하지 않는 페이지로 접근시 메인 페이지로 리다이렉트 됩니다.
- 로그인하지 않은 사용자가 모임 상세 페이지에 접근할시 ArrowIcon이 보이지 않습니다.
- Resolves #93
=> 🐛 Fix - 모임 삭제/종료/나가기 alert 제거, 모임 생성 단계에서 좌표의 주소가 즉각적으로 업데이트 되지 않는 오류 픽스 외 3건
